"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.order = exports.cart = exports.like = exports.category = exports.books = exports.users = void 0;
var user_route_1 = require("../apps/users/user-route");
exports.users = user_route_1.default;
var books_route_1 = require("../apps/books/books-route");
exports.books = books_route_1.default;
var category_route_1 = require("../apps/categories/category-route");
exports.category = category_route_1.default;
var like_route_1 = require("../apps/like/like-route");
exports.like = like_route_1.default;
var cart_route_1 = require("../apps/carts/cart-route");
exports.cart = cart_route_1.default;
var order_route_1 = require("../apps/order/order-route");
exports.order = order_route_1.default;
