"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.order = exports.cart = exports.like = exports.category = exports.books = exports.users = void 0;
var user_service_1 = require("./user-service");
exports.users = user_service_1.default;
var books_service_1 = require("./books-service");
exports.books = books_service_1.default;
var category_service_1 = require("./category-service");
exports.category = category_service_1.default;
var like_service_1 = require("./like-service");
exports.like = like_service_1.default;
var cart_servcie_1 = require("./cart-servcie");
exports.cart = cart_servcie_1.default;
var order_service_1 = require("./order-service");
exports.order = order_service_1.default;
